# Generated by Django 3.2.9 on 2021-11-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_no',
            field=models.IntegerField(),
        ),
    ]
