# Generated by Django 3.2.9 on 2021-11-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_mileage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_phot1',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_phot2',
            new_name='photo1',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_phot3',
            new_name='photo2',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_phot4',
            new_name='photo3',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_photo',
            new_name='photo4',
        ),
    ]
