# Generated by Django 3.2.9 on 2021-11-10 12:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20211110_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio', 'Audio'), ('Airbags', 'Airbags'), ('AC', 'AC'), ('Seat Heating', 'Seat Heating'), ('Seat Massage', 'Seat Massage'), ('Alarm System', 'Alarm System'), ('Parking Assist', 'Parking Assist'), ('Power Steering', 'Power Steering'), ('Backup Camera', 'Backup Camera'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth', 'Bluetooth'), ('Electric Charge', 'Electric Charge')], max_length=156),
        ),
    ]
