# Generated by Django 3.2.9 on 2021-11-10 18:46

import ckeditor.fields
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Navigation System', 'Navigation System'), ('Audio', 'Audio'), ('Airbags', 'Airbags'), ('AC', 'AC'), ('Heated Seats', 'Heated Seats'), ('Seat Massage', 'Seat Massage'), ('Alarm System', 'Alarm System'), ('Parking Assist', 'Parking Assist'), ('Power Steering', 'Power Steering'), ('Backup Camera', 'Backup Camera'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth', 'Bluetooth'), ('Keyless Entry', 'Keyless Entry'), ('Electric Charging', 'Electric Charging'), ('Leather Seats', 'Leather Seats')], max_length=189),
        ),
    ]
