# Generated by Django 2.2.12 on 2021-12-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_car_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_number',
            field=models.CharField(max_length=50),
        ),
    ]
